import React,{useEffect,useState} from "react";
import {Routes,Route,Link,useNavigate,Navigate} from "react-router-dom";
import {MapContainer,TileLayer,Marker,Popup,useMapEvents} from "react-leaflet";
import L from "leaflet";
import api from "./api";

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
 iconRetinaUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
 iconUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
 shadowUrl:"https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png"
});

const categories=["Beach","Mountains","City","Historical","Adventure","Food","Other"];

function Protected({children}){return localStorage.getItem("token")?children:<Navigate to="/login"/>}
function Nav(){const nav=useNavigate();return <nav><Link to="/" className="brand">✈ Travel Bucket</Link><div><Link to="/">Dashboard</Link><Link to="/destinations">Destinations</Link><Link to="/trips">Trips</Link><button onClick={()=>{localStorage.clear();nav("/login")}}>Logout</button></div></nav>}
function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await api.post("/auth/login",{email,password});localStorage.setItem("token",r.data.access_token);nav("/")}catch(x){alert(x.response?.data?.error||"Login failed")}};return <Auth title="Welcome back" submit={submit}><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/></Auth>}
function Register(){const [name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),nav=useNavigate();const submit=async e=>{e.preventDefault();try{await api.post("/auth/register",{name,email,password});nav("/login")}catch(x){alert(x.response?.data?.error||"Registration failed")}};return <Auth title="Create account" submit={submit}><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/></Auth>}
function Auth({title,submit,children}){return <div className="auth"><form onSubmit={submit}><h1>{title}</h1>{children}<button className="primary">Continue</button><p><Link to="/register">Register</Link> · <Link to="/login">Login</Link></p></form></div>}

function MapClick({onClick}){useMapEvents({click:e=>onClick(e.latlng)});return null}
function Map({items,onMapClick}){return <MapContainer center={[20,0]} zoom={2} className="map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapClick onClick={onMapClick}/>{items.map(d=><Marker key={d.id} position={[d.latitude,d.longitude]}><Popup><b>{d.name}</b><br/>{d.city}{d.city&&d.country?", ":""}{d.country}<br/>{d.visited?"Visited":"Wishlist"}</Popup></Marker>)}</MapContainer>}

function Dashboard(){const [stats,setStats]=useState({});const [items,setItems]=useState([]);useEffect(()=>{Promise.all([api.get("/dashboard/stats"),api.get("/destinations")]).then(([a,b])=>{setStats(a.data);setItems(b.data)})},[]);return <><Nav/><main><h1>Your Travel Dashboard</h1><div className="stats">{[["Destinations",stats.destinations],["Visited",stats.visited],["Wishlist",stats.wishlist],["Trips",stats.trips],["Countries",stats.countries]].map(x=><div className="stat"><small>{x[0]}</small><strong>{x[1]??0}</strong></div>)}</div><div className="card"><h2>Explore your map</h2><Map items={items}/></div></main></>}
function Destinations(){const [items,setItems]=useState([]),[form,setForm]=useState({name:"",city:"",country:"",latitude:"",longitude:"",category:"Other",priority:"Medium",visited:false,notes:""});const load=()=>api.get("/destinations").then(r=>setItems(r.data));useEffect(load,[]);const save=async e=>{e.preventDefault();await api.post("/destinations",form);setForm({...form,name:"",city:"",country:"",latitude:"",longitude:"",notes:""});load()};const del=async id=>{if(confirm("Delete destination?")){await api.delete(`/destinations/${id}`);load()}};return <><Nav/><main><div className="split"><section><h1>Destinations</h1><form className="card form" onSubmit={save}><input required placeholder="Destination name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="row"><input placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></div><div className="row"><input required type="number" step="any" placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input required type="number" step="any" placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></div><div className="row"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option>{c}</option>)}</select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select></div><textarea placeholder="Travel notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><label><input type="checkbox" checked={form.visited} onChange={e=>setForm({...form,visited:e.target.checked})}/> Visited</label><button className="primary">Add destination</button></form></section><section><Map items={items}/><div className="list">{items.map(d=><div className="destination"><div><b>{d.name}</b><span>{d.city}{d.city&&d.country?", ":""}{d.country}</span><small>{d.category} · {d.priority} · {d.visited?"Visited":"Wishlist"}</small></div><button onClick={()=>del(d.id)}>Delete</button></div>)}</div></section></div></main></>}
function Trips(){const [trips,setTrips]=useState([]),[name,setName]=useState(""),load=()=>api.get("/trips").then(r=>setTrips(r.data));useEffect(load,[]);const add=async e=>{e.preventDefault();await api.post("/trips",{name});setName("");load()};const del=async id=>{await api.delete(`/trips/${id}`);load()};return <><Nav/><main><h1>Trips</h1><form className="card row" onSubmit={add}><input required placeholder="Trip name" value={name} onChange={e=>setName(e.target.value)}/><button className="primary">Create trip</button></form><div className="grid">{trips.map(t=><div className="card"><h2>{t.name}</h2><p>{t.status}</p><p>{t.destinations.length} destinations</p><button onClick={()=>del(t.id)}>Delete</button></div>)}</div></main></>}

export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/destinations" element={<Protected><Destinations/></Protected>}/><Route path="/trips" element={<Protected><Trips/></Protected>}/></Routes>}
